
package lexmodelsv2

import (
    "github.com/aws/aws-sdk-go-v2/service/lexmodelsv2"
)

// IClient defines the interface for lexmodelsv2
type IClient interface {
 Options() Options 
 BatchCreateCustomVocabularyItem(ctx context.Context, params *BatchCreateCustomVocabularyItemInput, optFns ...func(*Options)) (*BatchCreateCustomVocabularyItemOutput, error) 
 BatchDeleteCustomVocabularyItem(ctx context.Context, params *BatchDeleteCustomVocabularyItemInput, optFns ...func(*Options)) (*BatchDeleteCustomVocabularyItemOutput, error) 
 BatchUpdateCustomVocabularyItem(ctx context.Context, params *BatchUpdateCustomVocabularyItemInput, optFns ...func(*Options)) (*BatchUpdateCustomVocabularyItemOutput, error) 
 BuildBotLocale(ctx context.Context, params *BuildBotLocaleInput, optFns ...func(*Options)) (*BuildBotLocaleOutput, error) 
 CreateBot(ctx context.Context, params *CreateBotInput, optFns ...func(*Options)) (*CreateBotOutput, error) 
 CreateBotAlias(ctx context.Context, params *CreateBotAliasInput, optFns ...func(*Options)) (*CreateBotAliasOutput, error) 
 CreateBotLocale(ctx context.Context, params *CreateBotLocaleInput, optFns ...func(*Options)) (*CreateBotLocaleOutput, error) 
 CreateBotReplica(ctx context.Context, params *CreateBotReplicaInput, optFns ...func(*Options)) (*CreateBotReplicaOutput, error) 
 CreateBotVersion(ctx context.Context, params *CreateBotVersionInput, optFns ...func(*Options)) (*CreateBotVersionOutput, error) 
 CreateExport(ctx context.Context, params *CreateExportInput, optFns ...func(*Options)) (*CreateExportOutput, error) 
 CreateIntent(ctx context.Context, params *CreateIntentInput, optFns ...func(*Options)) (*CreateIntentOutput, error) 
 CreateResourcePolicy(ctx context.Context, params *CreateResourcePolicyInput, optFns ...func(*Options)) (*CreateResourcePolicyOutput, error) 
 CreateResourcePolicyStatement(ctx context.Context, params *CreateResourcePolicyStatementInput, optFns ...func(*Options)) (*CreateResourcePolicyStatementOutput, error) 
 CreateSlot(ctx context.Context, params *CreateSlotInput, optFns ...func(*Options)) (*CreateSlotOutput, error) 
 CreateSlotType(ctx context.Context, params *CreateSlotTypeInput, optFns ...func(*Options)) (*CreateSlotTypeOutput, error) 
 CreateTestSetDiscrepancyReport(ctx context.Context, params *CreateTestSetDiscrepancyReportInput, optFns ...func(*Options)) (*CreateTestSetDiscrepancyReportOutput, error) 
 CreateUploadUrl(ctx context.Context, params *CreateUploadUrlInput, optFns ...func(*Options)) (*CreateUploadUrlOutput, error) 
 DeleteBot(ctx context.Context, params *DeleteBotInput, optFns ...func(*Options)) (*DeleteBotOutput, error) 
 DeleteBotAlias(ctx context.Context, params *DeleteBotAliasInput, optFns ...func(*Options)) (*DeleteBotAliasOutput, error) 
 DeleteBotLocale(ctx context.Context, params *DeleteBotLocaleInput, optFns ...func(*Options)) (*DeleteBotLocaleOutput, error) 
 DeleteBotReplica(ctx context.Context, params *DeleteBotReplicaInput, optFns ...func(*Options)) (*DeleteBotReplicaOutput, error) 
 DeleteBotVersion(ctx context.Context, params *DeleteBotVersionInput, optFns ...func(*Options)) (*DeleteBotVersionOutput, error) 
 DeleteCustomVocabulary(ctx context.Context, params *DeleteCustomVocabularyInput, optFns ...func(*Options)) (*DeleteCustomVocabularyOutput, error) 
 DeleteExport(ctx context.Context, params *DeleteExportInput, optFns ...func(*Options)) (*DeleteExportOutput, error) 
 DeleteImport(ctx context.Context, params *DeleteImportInput, optFns ...func(*Options)) (*DeleteImportOutput, error) 
 DeleteIntent(ctx context.Context, params *DeleteIntentInput, optFns ...func(*Options)) (*DeleteIntentOutput, error) 
 DeleteResourcePolicy(ctx context.Context, params *DeleteResourcePolicyInput, optFns ...func(*Options)) (*DeleteResourcePolicyOutput, error) 
 DeleteResourcePolicyStatement(ctx context.Context, params *DeleteResourcePolicyStatementInput, optFns ...func(*Options)) (*DeleteResourcePolicyStatementOutput, error) 
 DeleteSlot(ctx context.Context, params *DeleteSlotInput, optFns ...func(*Options)) (*DeleteSlotOutput, error) 
 DeleteSlotType(ctx context.Context, params *DeleteSlotTypeInput, optFns ...func(*Options)) (*DeleteSlotTypeOutput, error) 
 DeleteTestSet(ctx context.Context, params *DeleteTestSetInput, optFns ...func(*Options)) (*DeleteTestSetOutput, error) 
 DeleteUtterances(ctx context.Context, params *DeleteUtterancesInput, optFns ...func(*Options)) (*DeleteUtterancesOutput, error) 
 DescribeBot(ctx context.Context, params *DescribeBotInput, optFns ...func(*Options)) (*DescribeBotOutput, error) 
 DescribeBotAlias(ctx context.Context, params *DescribeBotAliasInput, optFns ...func(*Options)) (*DescribeBotAliasOutput, error) 
 DescribeBotLocale(ctx context.Context, params *DescribeBotLocaleInput, optFns ...func(*Options)) (*DescribeBotLocaleOutput, error) 
 DescribeBotRecommendation(ctx context.Context, params *DescribeBotRecommendationInput, optFns ...func(*Options)) (*DescribeBotRecommendationOutput, error) 
 DescribeBotReplica(ctx context.Context, params *DescribeBotReplicaInput, optFns ...func(*Options)) (*DescribeBotReplicaOutput, error) 
 DescribeBotResourceGeneration(ctx context.Context, params *DescribeBotResourceGenerationInput, optFns ...func(*Options)) (*DescribeBotResourceGenerationOutput, error) 
 DescribeBotVersion(ctx context.Context, params *DescribeBotVersionInput, optFns ...func(*Options)) (*DescribeBotVersionOutput, error) 
 DescribeCustomVocabularyMetadata(ctx context.Context, params *DescribeCustomVocabularyMetadataInput, optFns ...func(*Options)) (*DescribeCustomVocabularyMetadataOutput, error) 
 DescribeExport(ctx context.Context, params *DescribeExportInput, optFns ...func(*Options)) (*DescribeExportOutput, error) 
 DescribeImport(ctx context.Context, params *DescribeImportInput, optFns ...func(*Options)) (*DescribeImportOutput, error) 
 DescribeIntent(ctx context.Context, params *DescribeIntentInput, optFns ...func(*Options)) (*DescribeIntentOutput, error) 
 DescribeResourcePolicy(ctx context.Context, params *DescribeResourcePolicyInput, optFns ...func(*Options)) (*DescribeResourcePolicyOutput, error) 
 DescribeSlot(ctx context.Context, params *DescribeSlotInput, optFns ...func(*Options)) (*DescribeSlotOutput, error) 
 DescribeSlotType(ctx context.Context, params *DescribeSlotTypeInput, optFns ...func(*Options)) (*DescribeSlotTypeOutput, error) 
 DescribeTestExecution(ctx context.Context, params *DescribeTestExecutionInput, optFns ...func(*Options)) (*DescribeTestExecutionOutput, error) 
 DescribeTestSet(ctx context.Context, params *DescribeTestSetInput, optFns ...func(*Options)) (*DescribeTestSetOutput, error) 
 DescribeTestSetDiscrepancyReport(ctx context.Context, params *DescribeTestSetDiscrepancyReportInput, optFns ...func(*Options)) (*DescribeTestSetDiscrepancyReportOutput, error) 
 DescribeTestSetGeneration(ctx context.Context, params *DescribeTestSetGenerationInput, optFns ...func(*Options)) (*DescribeTestSetGenerationOutput, error) 
 GenerateBotElement(ctx context.Context, params *GenerateBotElementInput, optFns ...func(*Options)) (*GenerateBotElementOutput, error) 
 GetTestExecutionArtifactsUrl(ctx context.Context, params *GetTestExecutionArtifactsUrlInput, optFns ...func(*Options)) (*GetTestExecutionArtifactsUrlOutput, error) 
 ListAggregatedUtterances(ctx context.Context, params *ListAggregatedUtterancesInput, optFns ...func(*Options)) (*ListAggregatedUtterancesOutput, error) 
 ListBotAliasReplicas(ctx context.Context, params *ListBotAliasReplicasInput, optFns ...func(*Options)) (*ListBotAliasReplicasOutput, error) 
 ListBotAliases(ctx context.Context, params *ListBotAliasesInput, optFns ...func(*Options)) (*ListBotAliasesOutput, error) 
 ListBotLocales(ctx context.Context, params *ListBotLocalesInput, optFns ...func(*Options)) (*ListBotLocalesOutput, error) 
 ListBotRecommendations(ctx context.Context, params *ListBotRecommendationsInput, optFns ...func(*Options)) (*ListBotRecommendationsOutput, error) 
 ListBotReplicas(ctx context.Context, params *ListBotReplicasInput, optFns ...func(*Options)) (*ListBotReplicasOutput, error) 
 ListBotResourceGenerations(ctx context.Context, params *ListBotResourceGenerationsInput, optFns ...func(*Options)) (*ListBotResourceGenerationsOutput, error) 
 ListBotVersionReplicas(ctx context.Context, params *ListBotVersionReplicasInput, optFns ...func(*Options)) (*ListBotVersionReplicasOutput, error) 
 ListBotVersions(ctx context.Context, params *ListBotVersionsInput, optFns ...func(*Options)) (*ListBotVersionsOutput, error) 
 ListBots(ctx context.Context, params *ListBotsInput, optFns ...func(*Options)) (*ListBotsOutput, error) 
 ListBuiltInIntents(ctx context.Context, params *ListBuiltInIntentsInput, optFns ...func(*Options)) (*ListBuiltInIntentsOutput, error) 
 ListBuiltInSlotTypes(ctx context.Context, params *ListBuiltInSlotTypesInput, optFns ...func(*Options)) (*ListBuiltInSlotTypesOutput, error) 
 ListCustomVocabularyItems(ctx context.Context, params *ListCustomVocabularyItemsInput, optFns ...func(*Options)) (*ListCustomVocabularyItemsOutput, error) 
 ListExports(ctx context.Context, params *ListExportsInput, optFns ...func(*Options)) (*ListExportsOutput, error) 
 ListImports(ctx context.Context, params *ListImportsInput, optFns ...func(*Options)) (*ListImportsOutput, error) 
 ListIntentMetrics(ctx context.Context, params *ListIntentMetricsInput, optFns ...func(*Options)) (*ListIntentMetricsOutput, error) 
 ListIntentPaths(ctx context.Context, params *ListIntentPathsInput, optFns ...func(*Options)) (*ListIntentPathsOutput, error) 
 ListIntentStageMetrics(ctx context.Context, params *ListIntentStageMetricsInput, optFns ...func(*Options)) (*ListIntentStageMetricsOutput, error) 
 ListIntents(ctx context.Context, params *ListIntentsInput, optFns ...func(*Options)) (*ListIntentsOutput, error) 
 ListRecommendedIntents(ctx context.Context, params *ListRecommendedIntentsInput, optFns ...func(*Options)) (*ListRecommendedIntentsOutput, error) 
 ListSessionAnalyticsData(ctx context.Context, params *ListSessionAnalyticsDataInput, optFns ...func(*Options)) (*ListSessionAnalyticsDataOutput, error) 
 ListSessionMetrics(ctx context.Context, params *ListSessionMetricsInput, optFns ...func(*Options)) (*ListSessionMetricsOutput, error) 
 ListSlotTypes(ctx context.Context, params *ListSlotTypesInput, optFns ...func(*Options)) (*ListSlotTypesOutput, error) 
 ListSlots(ctx context.Context, params *ListSlotsInput, optFns ...func(*Options)) (*ListSlotsOutput, error) 
 ListTagsForResource(ctx context.Context, params *ListTagsForResourceInput, optFns ...func(*Options)) (*ListTagsForResourceOutput, error) 
 ListTestExecutionResultItems(ctx context.Context, params *ListTestExecutionResultItemsInput, optFns ...func(*Options)) (*ListTestExecutionResultItemsOutput, error) 
 ListTestExecutions(ctx context.Context, params *ListTestExecutionsInput, optFns ...func(*Options)) (*ListTestExecutionsOutput, error) 
 ListTestSetRecords(ctx context.Context, params *ListTestSetRecordsInput, optFns ...func(*Options)) (*ListTestSetRecordsOutput, error) 
 ListTestSets(ctx context.Context, params *ListTestSetsInput, optFns ...func(*Options)) (*ListTestSetsOutput, error) 
 ListUtteranceAnalyticsData(ctx context.Context, params *ListUtteranceAnalyticsDataInput, optFns ...func(*Options)) (*ListUtteranceAnalyticsDataOutput, error) 
 ListUtteranceMetrics(ctx context.Context, params *ListUtteranceMetricsInput, optFns ...func(*Options)) (*ListUtteranceMetricsOutput, error) 
 SearchAssociatedTranscripts(ctx context.Context, params *SearchAssociatedTranscriptsInput, optFns ...func(*Options)) (*SearchAssociatedTranscriptsOutput, error) 
 StartBotRecommendation(ctx context.Context, params *StartBotRecommendationInput, optFns ...func(*Options)) (*StartBotRecommendationOutput, error) 
 StartBotResourceGeneration(ctx context.Context, params *StartBotResourceGenerationInput, optFns ...func(*Options)) (*StartBotResourceGenerationOutput, error) 
 StartImport(ctx context.Context, params *StartImportInput, optFns ...func(*Options)) (*StartImportOutput, error) 
 StartTestExecution(ctx context.Context, params *StartTestExecutionInput, optFns ...func(*Options)) (*StartTestExecutionOutput, error) 
 StartTestSetGeneration(ctx context.Context, params *StartTestSetGenerationInput, optFns ...func(*Options)) (*StartTestSetGenerationOutput, error) 
 StopBotRecommendation(ctx context.Context, params *StopBotRecommendationInput, optFns ...func(*Options)) (*StopBotRecommendationOutput, error) 
 TagResource(ctx context.Context, params *TagResourceInput, optFns ...func(*Options)) (*TagResourceOutput, error) 
 UntagResource(ctx context.Context, params *UntagResourceInput, optFns ...func(*Options)) (*UntagResourceOutput, error) 
 UpdateBot(ctx context.Context, params *UpdateBotInput, optFns ...func(*Options)) (*UpdateBotOutput, error) 
 UpdateBotAlias(ctx context.Context, params *UpdateBotAliasInput, optFns ...func(*Options)) (*UpdateBotAliasOutput, error) 
 UpdateBotLocale(ctx context.Context, params *UpdateBotLocaleInput, optFns ...func(*Options)) (*UpdateBotLocaleOutput, error) 
 UpdateBotRecommendation(ctx context.Context, params *UpdateBotRecommendationInput, optFns ...func(*Options)) (*UpdateBotRecommendationOutput, error) 
 UpdateExport(ctx context.Context, params *UpdateExportInput, optFns ...func(*Options)) (*UpdateExportOutput, error) 
 UpdateIntent(ctx context.Context, params *UpdateIntentInput, optFns ...func(*Options)) (*UpdateIntentOutput, error) 
 UpdateResourcePolicy(ctx context.Context, params *UpdateResourcePolicyInput, optFns ...func(*Options)) (*UpdateResourcePolicyOutput, error) 
 UpdateSlot(ctx context.Context, params *UpdateSlotInput, optFns ...func(*Options)) (*UpdateSlotOutput, error) 
 UpdateSlotType(ctx context.Context, params *UpdateSlotTypeInput, optFns ...func(*Options)) (*UpdateSlotTypeOutput, error) 
 UpdateTestSet(ctx context.Context, params *UpdateTestSetInput, optFns ...func(*Options)) (*UpdateTestSetOutput, error) 
}
