
package wellarchitected

import (
    "github.com/aws/aws-sdk-go-v2/service/wellarchitected"
)

// IClient defines the interface for wellarchitected
type IClient interface {
 Options() Options 
 AssociateLenses(ctx context.Context, params *AssociateLensesInput, optFns ...func(*Options)) (*AssociateLensesOutput, error) 
 AssociateProfiles(ctx context.Context, params *AssociateProfilesInput, optFns ...func(*Options)) (*AssociateProfilesOutput, error) 
 CreateLensShare(ctx context.Context, params *CreateLensShareInput, optFns ...func(*Options)) (*CreateLensShareOutput, error) 
 CreateLensVersion(ctx context.Context, params *CreateLensVersionInput, optFns ...func(*Options)) (*CreateLensVersionOutput, error) 
 CreateMilestone(ctx context.Context, params *CreateMilestoneInput, optFns ...func(*Options)) (*CreateMilestoneOutput, error) 
 CreateProfile(ctx context.Context, params *CreateProfileInput, optFns ...func(*Options)) (*CreateProfileOutput, error) 
 CreateProfileShare(ctx context.Context, params *CreateProfileShareInput, optFns ...func(*Options)) (*CreateProfileShareOutput, error) 
 CreateReviewTemplate(ctx context.Context, params *CreateReviewTemplateInput, optFns ...func(*Options)) (*CreateReviewTemplateOutput, error) 
 CreateTemplateShare(ctx context.Context, params *CreateTemplateShareInput, optFns ...func(*Options)) (*CreateTemplateShareOutput, error) 
 CreateWorkload(ctx context.Context, params *CreateWorkloadInput, optFns ...func(*Options)) (*CreateWorkloadOutput, error) 
 CreateWorkloadShare(ctx context.Context, params *CreateWorkloadShareInput, optFns ...func(*Options)) (*CreateWorkloadShareOutput, error) 
 DeleteLens(ctx context.Context, params *DeleteLensInput, optFns ...func(*Options)) (*DeleteLensOutput, error) 
 DeleteLensShare(ctx context.Context, params *DeleteLensShareInput, optFns ...func(*Options)) (*DeleteLensShareOutput, error) 
 DeleteProfile(ctx context.Context, params *DeleteProfileInput, optFns ...func(*Options)) (*DeleteProfileOutput, error) 
 DeleteProfileShare(ctx context.Context, params *DeleteProfileShareInput, optFns ...func(*Options)) (*DeleteProfileShareOutput, error) 
 DeleteReviewTemplate(ctx context.Context, params *DeleteReviewTemplateInput, optFns ...func(*Options)) (*DeleteReviewTemplateOutput, error) 
 DeleteTemplateShare(ctx context.Context, params *DeleteTemplateShareInput, optFns ...func(*Options)) (*DeleteTemplateShareOutput, error) 
 DeleteWorkload(ctx context.Context, params *DeleteWorkloadInput, optFns ...func(*Options)) (*DeleteWorkloadOutput, error) 
 DeleteWorkloadShare(ctx context.Context, params *DeleteWorkloadShareInput, optFns ...func(*Options)) (*DeleteWorkloadShareOutput, error) 
 DisassociateLenses(ctx context.Context, params *DisassociateLensesInput, optFns ...func(*Options)) (*DisassociateLensesOutput, error) 
 DisassociateProfiles(ctx context.Context, params *DisassociateProfilesInput, optFns ...func(*Options)) (*DisassociateProfilesOutput, error) 
 ExportLens(ctx context.Context, params *ExportLensInput, optFns ...func(*Options)) (*ExportLensOutput, error) 
 GetAnswer(ctx context.Context, params *GetAnswerInput, optFns ...func(*Options)) (*GetAnswerOutput, error) 
 GetConsolidatedReport(ctx context.Context, params *GetConsolidatedReportInput, optFns ...func(*Options)) (*GetConsolidatedReportOutput, error) 
 GetGlobalSettings(ctx context.Context, params *GetGlobalSettingsInput, optFns ...func(*Options)) (*GetGlobalSettingsOutput, error) 
 GetLens(ctx context.Context, params *GetLensInput, optFns ...func(*Options)) (*GetLensOutput, error) 
 GetLensReview(ctx context.Context, params *GetLensReviewInput, optFns ...func(*Options)) (*GetLensReviewOutput, error) 
 GetLensReviewReport(ctx context.Context, params *GetLensReviewReportInput, optFns ...func(*Options)) (*GetLensReviewReportOutput, error) 
 GetLensVersionDifference(ctx context.Context, params *GetLensVersionDifferenceInput, optFns ...func(*Options)) (*GetLensVersionDifferenceOutput, error) 
 GetMilestone(ctx context.Context, params *GetMilestoneInput, optFns ...func(*Options)) (*GetMilestoneOutput, error) 
 GetProfile(ctx context.Context, params *GetProfileInput, optFns ...func(*Options)) (*GetProfileOutput, error) 
 GetProfileTemplate(ctx context.Context, params *GetProfileTemplateInput, optFns ...func(*Options)) (*GetProfileTemplateOutput, error) 
 GetReviewTemplate(ctx context.Context, params *GetReviewTemplateInput, optFns ...func(*Options)) (*GetReviewTemplateOutput, error) 
 GetReviewTemplateAnswer(ctx context.Context, params *GetReviewTemplateAnswerInput, optFns ...func(*Options)) (*GetReviewTemplateAnswerOutput, error) 
 GetReviewTemplateLensReview(ctx context.Context, params *GetReviewTemplateLensReviewInput, optFns ...func(*Options)) (*GetReviewTemplateLensReviewOutput, error) 
 GetWorkload(ctx context.Context, params *GetWorkloadInput, optFns ...func(*Options)) (*GetWorkloadOutput, error) 
 ImportLens(ctx context.Context, params *ImportLensInput, optFns ...func(*Options)) (*ImportLensOutput, error) 
 ListAnswers(ctx context.Context, params *ListAnswersInput, optFns ...func(*Options)) (*ListAnswersOutput, error) 
 ListCheckDetails(ctx context.Context, params *ListCheckDetailsInput, optFns ...func(*Options)) (*ListCheckDetailsOutput, error) 
 ListCheckSummaries(ctx context.Context, params *ListCheckSummariesInput, optFns ...func(*Options)) (*ListCheckSummariesOutput, error) 
 ListLensReviewImprovements(ctx context.Context, params *ListLensReviewImprovementsInput, optFns ...func(*Options)) (*ListLensReviewImprovementsOutput, error) 
 ListLensReviews(ctx context.Context, params *ListLensReviewsInput, optFns ...func(*Options)) (*ListLensReviewsOutput, error) 
 ListLensShares(ctx context.Context, params *ListLensSharesInput, optFns ...func(*Options)) (*ListLensSharesOutput, error) 
 ListLenses(ctx context.Context, params *ListLensesInput, optFns ...func(*Options)) (*ListLensesOutput, error) 
 ListMilestones(ctx context.Context, params *ListMilestonesInput, optFns ...func(*Options)) (*ListMilestonesOutput, error) 
 ListNotifications(ctx context.Context, params *ListNotificationsInput, optFns ...func(*Options)) (*ListNotificationsOutput, error) 
 ListProfileNotifications(ctx context.Context, params *ListProfileNotificationsInput, optFns ...func(*Options)) (*ListProfileNotificationsOutput, error) 
 ListProfileShares(ctx context.Context, params *ListProfileSharesInput, optFns ...func(*Options)) (*ListProfileSharesOutput, error) 
 ListProfiles(ctx context.Context, params *ListProfilesInput, optFns ...func(*Options)) (*ListProfilesOutput, error) 
 ListReviewTemplateAnswers(ctx context.Context, params *ListReviewTemplateAnswersInput, optFns ...func(*Options)) (*ListReviewTemplateAnswersOutput, error) 
 ListReviewTemplates(ctx context.Context, params *ListReviewTemplatesInput, optFns ...func(*Options)) (*ListReviewTemplatesOutput, error) 
 ListShareInvitations(ctx context.Context, params *ListShareInvitationsInput, optFns ...func(*Options)) (*ListShareInvitationsOutput, error) 
 ListTagsForResource(ctx context.Context, params *ListTagsForResourceInput, optFns ...func(*Options)) (*ListTagsForResourceOutput, error) 
 ListTemplateShares(ctx context.Context, params *ListTemplateSharesInput, optFns ...func(*Options)) (*ListTemplateSharesOutput, error) 
 ListWorkloadShares(ctx context.Context, params *ListWorkloadSharesInput, optFns ...func(*Options)) (*ListWorkloadSharesOutput, error) 
 ListWorkloads(ctx context.Context, params *ListWorkloadsInput, optFns ...func(*Options)) (*ListWorkloadsOutput, error) 
 TagResource(ctx context.Context, params *TagResourceInput, optFns ...func(*Options)) (*TagResourceOutput, error) 
 UntagResource(ctx context.Context, params *UntagResourceInput, optFns ...func(*Options)) (*UntagResourceOutput, error) 
 UpdateAnswer(ctx context.Context, params *UpdateAnswerInput, optFns ...func(*Options)) (*UpdateAnswerOutput, error) 
 UpdateGlobalSettings(ctx context.Context, params *UpdateGlobalSettingsInput, optFns ...func(*Options)) (*UpdateGlobalSettingsOutput, error) 
 UpdateIntegration(ctx context.Context, params *UpdateIntegrationInput, optFns ...func(*Options)) (*UpdateIntegrationOutput, error) 
 UpdateLensReview(ctx context.Context, params *UpdateLensReviewInput, optFns ...func(*Options)) (*UpdateLensReviewOutput, error) 
 UpdateProfile(ctx context.Context, params *UpdateProfileInput, optFns ...func(*Options)) (*UpdateProfileOutput, error) 
 UpdateReviewTemplate(ctx context.Context, params *UpdateReviewTemplateInput, optFns ...func(*Options)) (*UpdateReviewTemplateOutput, error) 
 UpdateReviewTemplateAnswer(ctx context.Context, params *UpdateReviewTemplateAnswerInput, optFns ...func(*Options)) (*UpdateReviewTemplateAnswerOutput, error) 
 UpdateReviewTemplateLensReview(ctx context.Context, params *UpdateReviewTemplateLensReviewInput, optFns ...func(*Options)) (*UpdateReviewTemplateLensReviewOutput, error) 
 UpdateShareInvitation(ctx context.Context, params *UpdateShareInvitationInput, optFns ...func(*Options)) (*UpdateShareInvitationOutput, error) 
 UpdateWorkload(ctx context.Context, params *UpdateWorkloadInput, optFns ...func(*Options)) (*UpdateWorkloadOutput, error) 
 UpdateWorkloadShare(ctx context.Context, params *UpdateWorkloadShareInput, optFns ...func(*Options)) (*UpdateWorkloadShareOutput, error) 
 UpgradeLensReview(ctx context.Context, params *UpgradeLensReviewInput, optFns ...func(*Options)) (*UpgradeLensReviewOutput, error) 
 UpgradeProfileVersion(ctx context.Context, params *UpgradeProfileVersionInput, optFns ...func(*Options)) (*UpgradeProfileVersionOutput, error) 
 UpgradeReviewTemplateLensReview(ctx context.Context, params *UpgradeReviewTemplateLensReviewInput, optFns ...func(*Options)) (*UpgradeReviewTemplateLensReviewOutput, error) 
}
