
package appstream

import (
    "github.com/aws/aws-sdk-go-v2/service/appstream"
)

// IAppstream defines the interface for appstream
type IAppstream interface {
 Options() Options 
 AssociateAppBlockBuilderAppBlock(ctx context.Context, params *AssociateAppBlockBuilderAppBlockInput, optFns ...func(*Options)) (*AssociateAppBlockBuilderAppBlockOutput, error) 
 AssociateApplicationFleet(ctx context.Context, params *AssociateApplicationFleetInput, optFns ...func(*Options)) (*AssociateApplicationFleetOutput, error) 
 AssociateApplicationToEntitlement(ctx context.Context, params *AssociateApplicationToEntitlementInput, optFns ...func(*Options)) (*AssociateApplicationToEntitlementOutput, error) 
 AssociateFleet(ctx context.Context, params *AssociateFleetInput, optFns ...func(*Options)) (*AssociateFleetOutput, error) 
 BatchAssociateUserStack(ctx context.Context, params *BatchAssociateUserStackInput, optFns ...func(*Options)) (*BatchAssociateUserStackOutput, error) 
 BatchDisassociateUserStack(ctx context.Context, params *BatchDisassociateUserStackInput, optFns ...func(*Options)) (*BatchDisassociateUserStackOutput, error) 
 CopyImage(ctx context.Context, params *CopyImageInput, optFns ...func(*Options)) (*CopyImageOutput, error) 
 CreateAppBlock(ctx context.Context, params *CreateAppBlockInput, optFns ...func(*Options)) (*CreateAppBlockOutput, error) 
 CreateAppBlockBuilder(ctx context.Context, params *CreateAppBlockBuilderInput, optFns ...func(*Options)) (*CreateAppBlockBuilderOutput, error) 
 CreateAppBlockBuilderStreamingURL(ctx context.Context, params *CreateAppBlockBuilderStreamingURLInput, optFns ...func(*Options)) (*CreateAppBlockBuilderStreamingURLOutput, error) 
 CreateApplication(ctx context.Context, params *CreateApplicationInput, optFns ...func(*Options)) (*CreateApplicationOutput, error) 
 CreateDirectoryConfig(ctx context.Context, params *CreateDirectoryConfigInput, optFns ...func(*Options)) (*CreateDirectoryConfigOutput, error) 
 CreateEntitlement(ctx context.Context, params *CreateEntitlementInput, optFns ...func(*Options)) (*CreateEntitlementOutput, error) 
 CreateFleet(ctx context.Context, params *CreateFleetInput, optFns ...func(*Options)) (*CreateFleetOutput, error) 
 CreateImageBuilder(ctx context.Context, params *CreateImageBuilderInput, optFns ...func(*Options)) (*CreateImageBuilderOutput, error) 
 CreateImageBuilderStreamingURL(ctx context.Context, params *CreateImageBuilderStreamingURLInput, optFns ...func(*Options)) (*CreateImageBuilderStreamingURLOutput, error) 
 CreateStack(ctx context.Context, params *CreateStackInput, optFns ...func(*Options)) (*CreateStackOutput, error) 
 CreateStreamingURL(ctx context.Context, params *CreateStreamingURLInput, optFns ...func(*Options)) (*CreateStreamingURLOutput, error) 
 CreateUpdatedImage(ctx context.Context, params *CreateUpdatedImageInput, optFns ...func(*Options)) (*CreateUpdatedImageOutput, error) 
 CreateUsageReportSubscription(ctx context.Context, params *CreateUsageReportSubscriptionInput, optFns ...func(*Options)) (*CreateUsageReportSubscriptionOutput, error) 
 CreateUser(ctx context.Context, params *CreateUserInput, optFns ...func(*Options)) (*CreateUserOutput, error) 
 DeleteAppBlock(ctx context.Context, params *DeleteAppBlockInput, optFns ...func(*Options)) (*DeleteAppBlockOutput, error) 
 DeleteAppBlockBuilder(ctx context.Context, params *DeleteAppBlockBuilderInput, optFns ...func(*Options)) (*DeleteAppBlockBuilderOutput, error) 
 DeleteApplication(ctx context.Context, params *DeleteApplicationInput, optFns ...func(*Options)) (*DeleteApplicationOutput, error) 
 DeleteDirectoryConfig(ctx context.Context, params *DeleteDirectoryConfigInput, optFns ...func(*Options)) (*DeleteDirectoryConfigOutput, error) 
 DeleteEntitlement(ctx context.Context, params *DeleteEntitlementInput, optFns ...func(*Options)) (*DeleteEntitlementOutput, error) 
 DeleteFleet(ctx context.Context, params *DeleteFleetInput, optFns ...func(*Options)) (*DeleteFleetOutput, error) 
 DeleteImage(ctx context.Context, params *DeleteImageInput, optFns ...func(*Options)) (*DeleteImageOutput, error) 
 DeleteImageBuilder(ctx context.Context, params *DeleteImageBuilderInput, optFns ...func(*Options)) (*DeleteImageBuilderOutput, error) 
 DeleteImagePermissions(ctx context.Context, params *DeleteImagePermissionsInput, optFns ...func(*Options)) (*DeleteImagePermissionsOutput, error) 
 DeleteStack(ctx context.Context, params *DeleteStackInput, optFns ...func(*Options)) (*DeleteStackOutput, error) 
 DeleteUsageReportSubscription(ctx context.Context, params *DeleteUsageReportSubscriptionInput, optFns ...func(*Options)) (*DeleteUsageReportSubscriptionOutput, error) 
 DeleteUser(ctx context.Context, params *DeleteUserInput, optFns ...func(*Options)) (*DeleteUserOutput, error) 
 DescribeAppBlockBuilderAppBlockAssociations(ctx context.Context, params *DescribeAppBlockBuilderAppBlockAssociationsInput, optFns ...func(*Options)) (*DescribeAppBlockBuilderAppBlockAssociationsOutput, error) 
 DescribeAppBlockBuilders(ctx context.Context, params *DescribeAppBlockBuildersInput, optFns ...func(*Options)) (*DescribeAppBlockBuildersOutput, error) 
 DescribeAppBlocks(ctx context.Context, params *DescribeAppBlocksInput, optFns ...func(*Options)) (*DescribeAppBlocksOutput, error) 
 DescribeApplicationFleetAssociations(ctx context.Context, params *DescribeApplicationFleetAssociationsInput, optFns ...func(*Options)) (*DescribeApplicationFleetAssociationsOutput, error) 
 DescribeApplications(ctx context.Context, params *DescribeApplicationsInput, optFns ...func(*Options)) (*DescribeApplicationsOutput, error) 
 DescribeDirectoryConfigs(ctx context.Context, params *DescribeDirectoryConfigsInput, optFns ...func(*Options)) (*DescribeDirectoryConfigsOutput, error) 
 DescribeEntitlements(ctx context.Context, params *DescribeEntitlementsInput, optFns ...func(*Options)) (*DescribeEntitlementsOutput, error) 
 DescribeFleets(ctx context.Context, params *DescribeFleetsInput, optFns ...func(*Options)) (*DescribeFleetsOutput, error) 
 DescribeImageBuilders(ctx context.Context, params *DescribeImageBuildersInput, optFns ...func(*Options)) (*DescribeImageBuildersOutput, error) 
 DescribeImagePermissions(ctx context.Context, params *DescribeImagePermissionsInput, optFns ...func(*Options)) (*DescribeImagePermissionsOutput, error) 
 DescribeImages(ctx context.Context, params *DescribeImagesInput, optFns ...func(*Options)) (*DescribeImagesOutput, error) 
 DescribeSessions(ctx context.Context, params *DescribeSessionsInput, optFns ...func(*Options)) (*DescribeSessionsOutput, error) 
 DescribeStacks(ctx context.Context, params *DescribeStacksInput, optFns ...func(*Options)) (*DescribeStacksOutput, error) 
 DescribeUsageReportSubscriptions(ctx context.Context, params *DescribeUsageReportSubscriptionsInput, optFns ...func(*Options)) (*DescribeUsageReportSubscriptionsOutput, error) 
 DescribeUserStackAssociations(ctx context.Context, params *DescribeUserStackAssociationsInput, optFns ...func(*Options)) (*DescribeUserStackAssociationsOutput, error) 
 DescribeUsers(ctx context.Context, params *DescribeUsersInput, optFns ...func(*Options)) (*DescribeUsersOutput, error) 
 DisableUser(ctx context.Context, params *DisableUserInput, optFns ...func(*Options)) (*DisableUserOutput, error) 
 DisassociateAppBlockBuilderAppBlock(ctx context.Context, params *DisassociateAppBlockBuilderAppBlockInput, optFns ...func(*Options)) (*DisassociateAppBlockBuilderAppBlockOutput, error) 
 DisassociateApplicationFleet(ctx context.Context, params *DisassociateApplicationFleetInput, optFns ...func(*Options)) (*DisassociateApplicationFleetOutput, error) 
 DisassociateApplicationFromEntitlement(ctx context.Context, params *DisassociateApplicationFromEntitlementInput, optFns ...func(*Options)) (*DisassociateApplicationFromEntitlementOutput, error) 
 DisassociateFleet(ctx context.Context, params *DisassociateFleetInput, optFns ...func(*Options)) (*DisassociateFleetOutput, error) 
 EnableUser(ctx context.Context, params *EnableUserInput, optFns ...func(*Options)) (*EnableUserOutput, error) 
 ExpireSession(ctx context.Context, params *ExpireSessionInput, optFns ...func(*Options)) (*ExpireSessionOutput, error) 
 ListAssociatedFleets(ctx context.Context, params *ListAssociatedFleetsInput, optFns ...func(*Options)) (*ListAssociatedFleetsOutput, error) 
 ListAssociatedStacks(ctx context.Context, params *ListAssociatedStacksInput, optFns ...func(*Options)) (*ListAssociatedStacksOutput, error) 
 ListEntitledApplications(ctx context.Context, params *ListEntitledApplicationsInput, optFns ...func(*Options)) (*ListEntitledApplicationsOutput, error) 
 ListTagsForResource(ctx context.Context, params *ListTagsForResourceInput, optFns ...func(*Options)) (*ListTagsForResourceOutput, error) 
 StartAppBlockBuilder(ctx context.Context, params *StartAppBlockBuilderInput, optFns ...func(*Options)) (*StartAppBlockBuilderOutput, error) 
 StartFleet(ctx context.Context, params *StartFleetInput, optFns ...func(*Options)) (*StartFleetOutput, error) 
 StartImageBuilder(ctx context.Context, params *StartImageBuilderInput, optFns ...func(*Options)) (*StartImageBuilderOutput, error) 
 StopAppBlockBuilder(ctx context.Context, params *StopAppBlockBuilderInput, optFns ...func(*Options)) (*StopAppBlockBuilderOutput, error) 
 StopFleet(ctx context.Context, params *StopFleetInput, optFns ...func(*Options)) (*StopFleetOutput, error) 
 StopImageBuilder(ctx context.Context, params *StopImageBuilderInput, optFns ...func(*Options)) (*StopImageBuilderOutput, error) 
 TagResource(ctx context.Context, params *TagResourceInput, optFns ...func(*Options)) (*TagResourceOutput, error) 
 UntagResource(ctx context.Context, params *UntagResourceInput, optFns ...func(*Options)) (*UntagResourceOutput, error) 
 UpdateAppBlockBuilder(ctx context.Context, params *UpdateAppBlockBuilderInput, optFns ...func(*Options)) (*UpdateAppBlockBuilderOutput, error) 
 UpdateApplication(ctx context.Context, params *UpdateApplicationInput, optFns ...func(*Options)) (*UpdateApplicationOutput, error) 
 UpdateDirectoryConfig(ctx context.Context, params *UpdateDirectoryConfigInput, optFns ...func(*Options)) (*UpdateDirectoryConfigOutput, error) 
 UpdateEntitlement(ctx context.Context, params *UpdateEntitlementInput, optFns ...func(*Options)) (*UpdateEntitlementOutput, error) 
 UpdateFleet(ctx context.Context, params *UpdateFleetInput, optFns ...func(*Options)) (*UpdateFleetOutput, error) 
 UpdateImagePermissions(ctx context.Context, params *UpdateImagePermissionsInput, optFns ...func(*Options)) (*UpdateImagePermissionsOutput, error) 
 UpdateStack(ctx context.Context, params *UpdateStackInput, optFns ...func(*Options)) (*UpdateStackOutput, error) 
}
